# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 10:56
from __future__ import unicode_literals

import contact_form.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Contact Request', help_text='Email subject for the contact form.', max_length=255, verbose_name='Subject')),
                ('email_to', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=254), default=contact_form.models.default_email_to, help_text='You can specify multiple mail address.Separate them with a comma. Max: 5 addresses', size=5, verbose_name='Send mail to')),
                ('email_from', models.EmailField(default='do_not_answer@emencia.com', max_length=254, verbose_name='Send contact email as')),
                ('success_html', models.TextField(default='<h2>Success</h2>\n<p>Thank you for your message, we will get back to you quickly !</p>', verbose_name='Success Message (in html)')),
            ],
            options={
                'verbose_name': 'Contact Form Settings',
                'verbose_name_plural': 'Contact Form Settings',
            },
        ),
    ]
