# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
        ('contact_form', '0002_contactformsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformsettings',
            name='site',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
