# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0003_contactformsettings_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformsettings',
            name='subject_en',
            field=models.CharField(default='Contact Request', help_text='Email subject for the contact form.', max_length=255, null=True, verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='contactformsettings',
            name='subject_fr',
            field=models.CharField(default='Contact Request', help_text='Email subject for the contact form.', max_length=255, null=True, verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='contactformsettings',
            name='success_html_en',
            field=models.TextField(default='<h2>Success</h2>\n<p>Thank you for your message, we will get back to you quickly !</p>', null=True, verbose_name='Success Message (in html)'),
        ),
        migrations.AddField(
            model_name='contactformsettings',
            name='success_html_fr',
            field=models.TextField(default='<h2>Success</h2>\n<p>Thank you for your message, we will get back to you quickly !</p>', null=True, verbose_name='Success Message (in html)'),
        ),
    ]
